CREATE
OR REPLACE TRIGGER TR_AUDIT_DECK_UPDATE
BEFORE UPDATE ON DECK
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_DECK(
        AUDIT_TYPE,
        DECK_ID,
        NAME,
        PASSWORD_HASH,
        IS_PUBLIC_READONLY,
        IS_LOBBY_WILD_DECK
    )
    VALUES (
        'UPDATE',
        OLD.ID,
        OLD.NAME,
        OLD.PASSWORD_HASH,
        OLD.IS_PUBLIC_READONLY,
        OLD.IS_LOBBY_WILD_DECK
    );
END;