CREATE
OR REPLACE TRIGGER TR_AUDIT_USER_UPDATE
BEFORE UPDATE ON USER
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_USER(
        AUDIT_TYPE,
        USER_ID,
        NAME,
        PASSWORD_HASH,
        COLOR_THEME,
        IS_APPROVED,
        IS_ADMIN
    )
    VALUES (
        'UPDATE',
        OLD.ID,
        OLD.NAME,
        OLD.PASSWORD_HASH,
        OLD.COLOR_THEME,
        OLD.IS_APPROVED,
        OLD.IS_ADMIN
    );
END;