CREATE
OR REPLACE TRIGGER TR_PLAYER_BEFORE_INSERT
BEFORE INSERT ON PLAYER
FOR EACH ROW
BEGIN
    SET NEW.JOIN_ORDER = (
            SELECT
                COUNT(*) + 1
            FROM PLAYER
            WHERE LOBBY_ID = NEW.LOBBY_ID
        );
END;