CREATE
OR REPLACE TRIGGER TR_REVOKE_ACCESS_AF_UP_DECK
AFTER UPDATE ON DECK
FOR EACH ROW
BEGIN
    IF OLD.PASSWORD_HASH <> NEW.PASSWORD_HASH THEN
        DELETE
        FROM USER_ACCESS_DECK
        WHERE DECK_ID = NEW.ID;
    END
    IF;
END;