CREATE TABLE IF NOT EXISTS AUDIT_DECK(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    AUDIT_TYPE ENUM('UPDATE', 'DELETE') NOT NULL,
    DECK_ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH CHAR(60) NOT NULL,
    IS_PUBLIC_READONLY BOOLEAN NOT NULL,
    IS_LOBBY_WILD_DECK BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);