CREATE TABLE IF NOT EXISTS AUDIT_USER(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    AUDIT_TYPE ENUM('UPDATE', 'DELETE') NOT NULL,
    USER_ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH CHAR(60) NOT NULL,
    COLOR_THEME VARCHAR(255) NULL,
    IS_APPROVED BOOLEAN NOT NULL,
    IS_ADMIN BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);