CREATE TABLE IF NOT EXISTS LOBBY(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    NAME VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR(255) NULL,
    PASSWORD_HASH CHAR(60) NULL,
    PRIMARY KEY(ID),
    CONSTRAINT NAME_UNIQUE UNIQUE(NAME)
);
