CREATE TABLE IF NOT EXISTS LOBBY_SETTINGS(
    LOBBY_ID UUID NOT NULL,
    TURN_TIMER_SECONDS INT NOT NULL DEFAULT 0,
    PRIMARY KEY(LOBBY_ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE
);
