CREATE TABLE IF NOT EXISTS PLAYER(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LOBBY_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    JOIN_ORDER INT NOT NULL DEFAULT 1,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT 1,
    WINNING_STREAK INT NOT NULL DEFAULT 0,
    LOSING_STREAK INT NOT NULL DEFAULT 0,
    CREDITS_SPENT INT NOT NULL DEFAULT 0,
    BET_ON_WIN INT NOT NULL DEFAULT 0,
    EXTRA_RESPONSES INT NOT NULL DEFAULT 0,
    LARGER_HAND_SIZE INT NOT NULL DEFAULT 0,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE,
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    CONSTRAINT LOBBY_USER_UNIQUE UNIQUE(LOBBY_ID, USER_ID)
);