CREATE TABLE IF NOT EXISTS USER_WIN_VIDEO(
    USER_ID UUID NOT NULL,
    CHANGED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    YOUTUBE_VIDEO_ID VARCHAR(11) NULL,
    START_OFFSET_SECONDS INT NOT NULL DEFAULT 0,
    PRIMARY KEY(USER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);
