CREATE TABLE IF NOT EXISTS USER_ACCESS_DECK(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USER_ID UUID NOT NULL,
    DECK_ID UUID NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY(DECK_ID) REFERENCES DECK(ID) ON DELETE CASCADE,
    CONSTRAINT USER_DECK_UNIQUE UNIQUE(USER_ID, DECK_ID)
);