CREATE TABLE IF NOT EXISTS USER_LOSE_CELEBRATION(
    USER_ID UUID NOT NULL,
    CHANGED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    GIF_DATA MEDIUMBLOB NULL,
    GIF_MIME VARCHAR(64) NULL,
    MESSAGE VARCHAR(1000) NULL,
    PRIMARY KEY(USER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);
