CREATE
OR REPLACE EVENT EVT_CLEAN_AUDIT_USER ON SCHEDULE EVERY 1 DAY
DO
    BEGIN
        DELETE
        FROM AUDIT_USER
        WHERE CREATED_ON_DATE < DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 WEEK);
    END;
