CREATE
OR REPLACE EVENT EVT_CLEAN_LOGIN_ATTEMPTS ON SCHEDULE EVERY 1 DAY
DO
    BEGIN
        DELETE
        FROM LOGIN_ATTEMPT
        WHERE CREATED_ON_DATE < DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 WEEK);
    END;