CREATE
OR REPLACE PROCEDURE SP_SET_PLAYER_INACTIVE(
    IN VAR_LOBBY_ID UUID,
    IN VAR_USER_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID DEFAULT (
            SELECT
                ID
            FROM PLAYER
            WHERE LOBBY_ID = VAR_LOBBY_ID
                AND USER_ID = VAR_USER_ID
        );

    UPDATE PLAYER
    SET IS_ACTIVE = 0
    WHERE ID = VAR_PLAYER_ID;
END;