#!/usr/bin/env bash
################################################################################
# Re-vendor the "Visual Assault" / "Tractor" theme blocks in
# static/css/colors.css from a specific VisualAssault tag.
#
# Usage: ./scripts/update-visual-assault-css.sh v0.3.0
#
# VisualAssault's packages/css/themes.css and this file's vendored section
# use identical `body.<theme-id>-theme { --color-...: ...; }` selectors, so
# this just downloads that file at the given tag and splices it in between
# the two marker comments below — it does not touch the "Classic" themes or
# the shared component rules above/below the vendored block.
################################################################################

set -e # exit on any command error

cd "$(dirname "$0")/.."

TAG="$1"
if [[ -z "$TAG" ]]; then
    echo "Usage: $(basename "$0") <visualassault-tag, e.g. v0.3.0>"
    exit 1
fi

COLORS_CSS="static/css/colors.css"
START_MARKER='/\* "Visual Assault" \/ "Tractor" themes'
URL="https://raw.githubusercontent.com/gerp93/VisualAssault/${TAG}/packages/css/themes.css"

echo "Fetching ${URL}..."
VENDORED=$(curl -fsSL "$URL")
if [[ -z "$VENDORED" ]]; then
    echo "Exiting: fetch returned no content — check the tag exists" >&2
    exit 1
fi

# Strip the generator header comment from VisualAssault's file; this
# script's own header comment (rewritten below) replaces it.
VENDORED=$(echo "$VENDORED" | sed '1{/^\/\* Generated by/d}' | sed '/./,$!d')

HEADER="/* \"Visual Assault\" / \"Tractor\" themes — vendored verbatim from
   https://github.com/gerp93/VisualAssault packages/css/themes.css @ ${TAG}.
   Do not hand-edit these blocks; re-run scripts/update-visual-assault-css.sh
   against a newer VisualAssault tag instead, then commit the diff as its
   own change so a version bump is reviewable on its own. */"

BEFORE=$(awk "/${START_MARKER}/{exit} {print}" "$COLORS_CSS")
AFTER=$(awk "/^body \{/{found=1} found{print}" "$COLORS_CSS")

{
    echo "$BEFORE"
    echo "$HEADER"
    echo
    echo "$VENDORED"
    echo "$AFTER"
} > "${COLORS_CSS}.new"
mv "${COLORS_CSS}.new" "$COLORS_CSS"

echo "Updated ${COLORS_CSS} to VisualAssault ${TAG}. Review the diff, then commit."
