CREATE
OR REPLACE FUNCTION FN_GET_LOGIN_ATTEMPT_IS_ALLOWED(
    IN VAR_IP_ADDRESS VARCHAR(255),
    IN VAR_USER_NAME VARCHAR(255)
)
RETURNS BOOLEAN
BEGIN
    DECLARE VAR_LOGIN_ATTEMPTS INT;

    SELECT
        COUNT(*)
    INTO
        VAR_LOGIN_ATTEMPTS
    FROM LOGIN_ATTEMPT
    WHERE (IP_ADDRESS = VAR_IP_ADDRESS OR USER_NAME = VAR_USER_NAME)
        AND CREATED_ON_DATE > DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR);

    RETURN VAR_LOGIN_ATTEMPTS < 10;
END;