CREATE
OR REPLACE FUNCTION FN_USER_HAS_LOBBY_ACCESS(
    IN VAR_USER_ID UUID,
    IN VAR_LOBBY_ID UUID
)
RETURNS BOOLEAN
BEGIN
    -- USER IS ADMIN
    IF EXISTS(SELECT ID FROM USER WHERE ID = VAR_USER_ID AND IS_ADMIN = 1) THEN
        RETURN 1;
    END
    IF;

    -- USER HAS ACCESS
    IF EXISTS(
        SELECT
            ID
        FROM USER_ACCESS_LOBBY
        WHERE USER_ID = VAR_USER_ID
            AND LOBBY_ID = VAR_LOBBY_ID
    ) THEN
        RETURN 1;
    END
    IF;

    -- LOBBY IS PASSWORD PROTECTED
    RETURN (SELECT PASSWORD_HASH IS NULL FROM LOBBY WHERE ID = VAR_LOBBY_ID);
END;