CREATE
OR REPLACE FUNCTION FN_USER_HAS_DECK_ACCESS(
    IN VAR_USER_ID UUID,
    IN VAR_DECK_ID UUID
)
RETURNS BOOLEAN
BEGIN
    -- USER IS ADMIN
    IF EXISTS(SELECT ID FROM USER WHERE ID = VAR_USER_ID AND IS_ADMIN = 1) THEN
        RETURN 1;
    END
    IF;

    -- USER HAS ACCESS
    IF EXISTS(
        SELECT
            ID
        FROM USER_ACCESS_DECK
        WHERE USER_ID = VAR_USER_ID
            AND DECK_ID = VAR_DECK_ID
    ) THEN
        RETURN 1;
    END
    IF;

    RETURN VAR_DECK_ID IS NULL;
END;